version: '3'
services: 
  redis: 
    image: redis
    container_name: redis_db
    env_file:
      - ./.env
    networks:
      - mrs-network

  postgres: 
    image: postgres 
    container_name: postgres_db 
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_DB=$PG_DATABASE
    ports: 
      - $PG_PORT:$PG_PORT
    volumes: 
      - ./postgres/data:/var/lib/postgres/data
      - ./scripts/mrs-init.sql:/docker-entrypoint-initdb.d/mrs-init.sql
    networks: 
      - mrs-network

  rabbitmq: 
    image: rabbitmq
    networks: 
      - mrs-network

  auth-service: 
    container_name: 'mrs-auth'
    depends_on:
        - postgres
    build: ./services/auth-service
    env_file:
      - ./.env
    ports: 
      - "3007:3007"
    links:
      - postgres
    
    volumes: 
      - ./services/auth-service:/auth-service
      - /auth-service/node_modules
    stdin_open: true
    tty: true
    networks: 
      - mrs-network
    
  
  booking-service: 
    container_name: 'mrs-booking'
    depends_on:
      - postgres
    build: ./services/booking-service
    ports: 
      - "3004:3004"
    volumes: 
      - ./services/booking-service:/app/services/booking-service
      - /app/node_modules
    env_file:
      - ./.env
    networks: 
      - mrs-network
    

  comment-service: 
    container_name: 'mrs-comment'
    depends_on:
      - postgres
    build: ./services/comment-service
    ports: 
      - "3010:3010"
    volumes: 
      - ./services/comment-service:/app/services/comment-service
      - /app/node_modules
    env_file:
      - ./.env
    networks: 
      - mrs-network
    

  movie-service: 
    container_name: 'mrs-movie'
    depends_on:
      - postgres
      - redis
    build: ./services/movie-service
    ports: 
      - "3002:3002"
    volumes: 
      - ./services/movie-service:/app/services/movie-service
      - /app/node_modules
    env_file:
      - ./.env
    networks: 
      - mrs-network
     

  offer-service: 
    container_name: 'mrs-offer'
    depends_on:
      - postgres
    build: ./services/offer-service
    ports: 
      - "3009:3009"
    volumes: 
      - ./services/offer-service:/app/services/offer-service
      - /app/node_modules
    env_file:
      - ./.env
    networks: 
      - mrs-network

  search-service: 
    container_name: 'mrs-search'
    depends_on:
      - postgres
    build: ./services/search-service
    ports: 
      - "3003:3003"
    volumes: 
      - ./services/search-service:/app/services/search-service
      - /app/node_modules
    env_file:
      - ./.env
    networks: 
      - mrs-network

  showtime-service: 
    container_name: 'mrs-showtime'
    depends_on:
      - postgres
    build: ./services/showtime-service
    ports: 
      - "3005:3005"
    volumes: 
      - ./services/showtime-service:/app/services/showtime-service
      - /app/node_modules
    env_file:
      - ./.env
    networks: 
      - mrs-network

  theater-service: 
    container_name: 'mrs-theater'
    depends_on:
      - postgres
      - redis
    build: ./services/theater-service
    ports: 
      - "3008:3008"
    volumes: 
      - ./services/theater-service:/app/services/theater-service
      - /app/node_modules
    env_file:
      - ./.env
    networks: 
      - mrs-network

  user-service: 
    container_name: 'mrs-user'
    depends_on:
      - postgres
    build: ./services/user-service
    ports: 
      - "3001:3001"
    volumes: 
      - ./services/user-service:/app/services/user-service
      - /app/node_modules
    env_file:
      - ./.env
    networks: 
      - mrs-network
  

networks:
  mrs-network:
    external: true